name: Snapshot build

on:
  push:
    branches-ignore:
      - 'release-**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'

      - uses: ./.github/actions/configure
        with:
          gpg-secret-key: ${{ secrets.OSSRH_GPG_SECRET_KEY }}
          gpg-keyid-last8: ${{ secrets.OSSRH_GPG_KEY_ID_LAST_8 }}
          gpg-secret-passphrase: ${{ secrets.OSSRH_GPG_SECRET_KEY_PASSPHRASE }}

      - uses: ./.github/actions/version
        id: version

      - name: Debug environment set from above
        run: |
          echo "BETA_VERSION = $BETA_VERSION"
          echo "PROMISE_SUFFIX = $PROMISE_SUFFIX"
          echo "PROMISE_VERSION = $PROMISE_VERSION"
          echo "PROMISE_CONFIGURED = $PROMISE_CONFIGURED"
          echo "VERSION_CONFIGURED = $VERSION_CONFIGURED"

      - name: Checks
        id: checks
        run: |
          bash ./scripts/runChecks.sh

      - name: Build and Install
        id: build
        run: |
          ./gradlew -PSUFFIX=$PROMISE_SUFFIX :promise:assembleRelease :promise:publishToMavenLocal
          ./gradlew -PSUFFIX=$PROMISE_SUFFIX :promise-ktx:assembleRelease :promise-ktx:publishToMavenLocal
          mkdir -p ./repository
          cp -r ~/.m2/repository/* ./repository
          zip -r repository.zip ./repository

      - name: Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: repository
          path: repository.zip

  release:
    runs-on: ubuntu-latest
    needs: build
    if: ${{ github.ref == 'refs/heads/master' || startsWith(github.ref, 'refs/heads/beta/') }}
    steps:

      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'

      - uses: ./.github/actions/configure
        with:
          gpg-secret-key: ${{ secrets.OSSRH_GPG_SECRET_KEY }}
          gpg-keyid-last8: ${{ secrets.OSSRH_GPG_KEY_ID_LAST_8 }}
          gpg-secret-passphrase: ${{ secrets.OSSRH_GPG_SECRET_KEY_PASSPHRASE }}

      - uses: ./.github/actions/version
        id: version
      
      - name: Check mandatory variables
        id: check
        run: |
          echo "${{ steps.version.outputs.promise }}"

      - name: Create release
        run: |
          echo "sonatypeUsername=${{ secrets.OSSRH_USERNAME }}" >> gradle.properties
          echo "sonatypePassword=${{ secrets.OSSRH_PASSWORD }}" >> gradle.properties
          export branch="${{ github.ref }}"
          ./gradlew -PSUFFIX=$PROMISE_SUFFIX :promise:assembleRelease :promise-ktx:assembleRelease
          ./gradlew -PSUFFIX=$PROMISE_SUFFIX publishToSonatype closeAndReleaseStagingRepository

      - name: Create Github's beta release
        id: automatic_beta
        if: startsWith(github.ref, 'refs/heads/beta/')
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "v${{ steps.version.outputs.promise }}"
          prerelease: true
          title: ${{ steps.version.outputs.promise }}

      - name: Create Github's master release
        id: automatic_master
        if: github.ref == 'refs/heads/master'
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "v${{ steps.version.outputs.promise }}"
          prerelease: false
          title: ${{ steps.version.outputs.promise }}
